In [28]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

# Part 1 : Data Leakge 
## Case 1 : Leakage via missing value 
If we have missing values in data and we tried to fill  it on entire dataset before filling it , then we have filled the missing values  with average of test data as well .

In [29]:
df_missing = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Score': [40, 60, np.nan, 80, np.nan, 90]  # Missing scores for C and E
})
print("Original data : ")
display(df_missing)
# first split data into testdata and train data
df_train,df_test=train_test_split(df_missing,test_size=0.2,random_state=42)
print("Training datset")
print()
display(df_train)
print("Testign data : ")
display(df_test)

Original data :

  Student  Score
0       A   40.0
1       B   60.0
2       C    NaN
3       D   80.0
4       E    NaN
5       F   90.0

Training datset

  Student  Score
5       F   90.0
2       C    NaN
4       E    NaN
3       D   80.0

Testign data :

  Student  Score
0       A   40.0
1       B   60.0

In [30]:
#  NOw take the average from training data and fill those values in both of the splited data
imputer=SimpleImputer(strategy="mean")
imputer.fit(df_train[["Score"]])
df_train["Score"]=imputer.transform(df_train[["Score"]])
df_test["Score"]=imputer.transform(df_test[["Score"]])
print("Filled test data : ")
display(df_test)
print("Filled trained data : ")
display(df_train)

Filled test data :

  Student  Score
0       A   40.0
1       B   60.0

Filled trained data :

  Student  Score
5       F   90.0
2       C   85.0
4       E   85.0
3       D   80.0

## Senerio 2 : Leakage through feature scaling 
Models like numbers to be small. We use MinMaxScaler to shrink numbers to be between 0 and 1.

The Formula: Scaled Value = (Value - Min) / (Max - Min)

Just like averages, the Min and Max MUST be learned from the Training data only!

In [41]:
data = pd.DataFrame({
    "attendance_pct": [92, 78, 95, 65, 88, 72, 90, 85, 91, 76, 82, 94, 68, 89, 74, 96, 71, 87, 93, 79],
    "assignment_avg": [82, 58, 90, 45, 75, 62, 88, 70, 85, 55, 78, 92, 48, 80, 60, 91, 52, 77, 89, 63],
    "target": [1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0], # 1 = Passed, 0 = Failed
})
print("Inspecting the missing values in whole data")
print(data.isnull().sum())
print(data.info())
print("-"*50)
print("No missing data in df")
print("-"*50)
# always first step is spliting the train ,  test data 
df_train,df_test=train_test_split(data,test_size=0.2,random_state=42)
#Start scaling
scaler=MinMaxScaler()
x=df_train[["attendance_pct","assignment_avg"]]
scaler.fit(x)
df_train[["attendance_pct","assignment_avg"]]=scaler.transform(df_train[["attendance_pct","assignment_avg"]])
df_test[["attendance_pct","assignment_avg"]]=scaler.transform(df_test[["attendance_pct","assignment_avg"]])
print("Scaled train :")
display(df_train)
print("Scaled test : ")
display(df_test)

Inspecting the missing values in whole data
attendance_pct    0
assignment_avg    0
target            0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   attendance_pct  20 non-null     int64
 1   assignment_avg  20 non-null     int64
 2   target          20 non-null     int64
dtypes: int64(3)
memory usage: 612.0 bytes
None
--------------------------------------------------
No missing data in df
--------------------------------------------------
Scaled train :

    attendance_pct  assignment_avg  target
8         0.866667        0.851064       1
5         0.233333        0.361702       0
11        0.966667        1.000000       1
3         0.000000        0.000000       0
18        0.933333        0.936170       1
16        0.200000        0.148936       0
13        0.800000        0.744681       1
2         1.000000        0.957447       1
9         0.366667        0.212766       0
19        0.466667        0.382979       0
4         0.766667        0.638298       1
12        0.100000        0.063830       0
7         0.666667        0.531915       1
10        0.566667        0.702128       1
14        0.300000        0.319149       0
6         0.833333        0.914894       1

Scaled test :

    attendance_pct  assignment_avg  target
0         0.900000        0.787234       1
17        0.733333        0.680851       1
15        1.033333        0.978723       1
1         0.433333        0.276596       0