In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split
from IPython.display import display

In [14]:
# 1. Car Dataset (Predicting car price)
data = {
    "Brand": ["Maruti", "Hyundai", "Maruti", "Honda", "Toyota", "Honda"],
    "Year": [2018, 2017, 2018, 2016, 2019, 2015],
    "Fuel": ["Petrol", "Diesel", "Petrol", "Petrol", "Diesel", "Petrol"],
    "KMs_Driven": [30000, 40000, 30000, None, 20000, 70000],
    "Price": [400000, 500000, 400000, 450000, 800000, -200000], # Notice: negative price, duplicate Maruti
}
df_car = pd.DataFrame(data)

# 2. Student Dataset (Understanding student performance)
data_student = {
    "Student_ID": ["S01", "S02", "S01", "S03", "S04"],
    "Marks": [85, 72, 85, None, 90],
    "Attendance": [90, 88, 90, 95, 92],
    "Grade": ["A", "B", "A", "C", -10], # Notice: weird -10 Grade, duplicate S01
}
df_student = pd.DataFrame(data_student)

# 3. E-commerce Dataset (Analyzing orders and pricing)
data_ecommerce = {
    "OrderID": ["O100", "O101", "O100", "O102", "O103"],
    "Product": ["Phone", "Laptop", "Phone", "Phone", "Laptop"],
    "Quantity": [1, 2, 1, None, 1],
    "Price": [20000, 60000, 20000, 15000, -5000], # Notice: negative price, missing quantity
}
df_ecom = pd.DataFrame(data_ecommerce)

print("Datasets loaded!")

Datasets loaded!

Inspecting the dataset

In [15]:
print("car Dataset")
print(df_car.head(5))
print("Structral summary of car data")
print(df_car.info())
print("Statictical summary of car data ")
print(df_car.describe())
print()

car Dataset
     Brand  Year    Fuel  KMs_Driven   Price
0   Maruti  2018  Petrol     30000.0  400000
1  Hyundai  2017  Diesel     40000.0  500000
2   Maruti  2018  Petrol     30000.0  400000
3    Honda  2016  Petrol         NaN  450000
4   Toyota  2019  Diesel     20000.0  800000
Structral summary of car data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Brand       6 non-null      object
 1   Year        6 non-null      int64
 2   Fuel        6 non-null      object
 3   KMs_Driven  5 non-null      float64
 4   Price       6 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes
None
Statictical summary of car data
              Year    KMs_Driven          Price
count     6.000000      5.000000       6.000000
mean   2017.166667  38000.000000  391666.666667
std       1.471960  19235.384062  326215.675078
min    2015.000000  20000.000000 -200000.000000
25%    2016.250000  30000.000000  400000.000000
50%    2017.500000  30000.000000  425000.000000
75%    2018.000000  40000.000000  487500.000000
max    2019.000000  70000.000000  800000.000000

In [16]:
#Cleaning the data
df_car=df_car.fillna(df_car["KMs_Driven"].mean())
df_car["Price"]=df_car["Price"].abs()
df_car=df_car.drop_duplicates()
print("Updated car dataset")
display(df_car)
print("<"*60)
# encoding
label_encoder = LabelEncoder()
df_car['Fuel'] = label_encoder.fit_transform(df_car['Fuel'])
print("Petrol=1,diesel=0")
df_car_encoded=pd.get_dummies(df_car,dtype=int,columns=["Brand"])
df_car_encoded
print("Encoded Dataset")
display(df_car_encoded)
# Scaling
columns_to_scale=["Year","KMs_Driven","Price"]
scaler=StandardScaler()
df_car_scaled=df_car_encoded.copy()
df_car_scaled[columns_to_scale]=scaler.fit_transform(df_car_encoded[columns_to_scale])
df_car_scaled=pd.DataFrame(df_car_scaled)
print("Scaled Dataset")
display(df_car_scaled)
# Train-Test spliting
x=df_car_scaled.drop("Price",axis=1)
y=df_car_scaled["Price"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4, random_state=42)

Updated car dataset

     Brand  Year    Fuel  KMs_Driven   Price
0   Maruti  2018  Petrol     30000.0  400000
1  Hyundai  2017  Diesel     40000.0  500000
3    Honda  2016  Petrol     38000.0  450000
4   Toyota  2019  Diesel     20000.0  800000
5    Honda  2015  Petrol     70000.0  200000

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Petrol=1,diesel=0
Encoded Dataset

,Year,Fuel,KMs_Driven,Price,Brand_Honda,Brand_Hyundai,Brand_Maruti,Brand_Toyota
0,2018,1,30000.0,400000,0,0,1,0
1,2017,0,40000.0,500000,0,1,0,0
3,2016,1,38000.0,450000,1,0,0,0
4,2019,0,20000.0,800000,0,0,0,1
5,2015,1,70000.0,200000,1,0,0,0

Scaled Dataset

,Year,Fuel,KMs_Driven,Price,Brand_Honda,Brand_Hyundai,Brand_Maruti,Brand_Toyota
0,0.707107,1,-0.573055,-0.360997,0,0,1,0
1,0.000000,0,0.023877,0.154713,0,1,0,0
3,-0.707107,1,-0.095509,-0.103142,1,0,0,0
4,1.414214,0,-1.169988,1.701845,0,0,0,1
5,-1.414214,1,1.814675,-1.392419,1,0,0,0

Inspecting the student dataset

In [17]:
print("-"*60)
print("Student Dataset")
display(df_student)
print("Structral summary of student data")
display(df_student.info())
print("Statictical summary of student data ")
print(df_student.describe())
print()

------------------------------------------------------------
Student Dataset

  Student_ID  Marks  Attendance Grade
0        S01   85.0          90     A
1        S02   72.0          88     B
2        S01   85.0          90     A
3        S03    NaN          95     C
4        S04   90.0          92   -10

Structral summary of student data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      object
 1   Marks       4 non-null      float64
 2   Attendance  5 non-null      int64
 3   Grade       5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

None

Statictical summary of student data
           Marks  Attendance
count   4.000000    5.000000
mean   83.000000   91.000000
std     7.702813    2.645751
min    72.000000   88.000000
25%    81.750000   90.000000
50%    85.000000   90.000000
75%    86.250000   92.000000
max    90.000000   95.000000

In [18]:
# Correcting the false data 
df_student["Grade"]=df_student["Grade"].replace({-10:np.nan,"-10":np.nan})
df_student["Marks"]=df_student["Marks"].abs()
df_student["Attendance"]=df_student["Attendance"].abs()
#handelling miissing values and duplicates
df_student["Marks"]=df_student["Marks"].fillna(df_student["Marks"].mean())
df_student["Grade"]=df_student["Grade"].fillna(df_student["Grade"].mode()[0])
df_student=df_student.drop_duplicates()
#Droping the id column 
df_student=df_student.drop("Student_ID",axis=1)
# encoding the columns
df_student_encoded=df_student.copy()
df_student_encoded=pd.get_dummies(df_student,dtype=int,columns=["Grade"])
#scaling
columns_to_scale=["Marks","Attendance"]
scaler=StandardScaler()
df_student_scaled=df_student_encoded.copy()
df_student_scaled[columns_to_scale]=scaler.fit_transform(df_student_encoded[columns_to_scale])
df_student_scaled=pd.DataFrame(df_student_scaled)
#Train,test spliting
x=df_student_scaled.drop("Marks",axis=1)
y=df_student_scaled["Marks"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

inspecting ecom database

In [19]:
print("-"*60)
print("E-commerce Dataset")
print(df_ecom.head(5))
print("Structral summary of e-commerce data")
print(df_ecom.info())
print("Statictical summary of e-commerce data ")
print(df_ecom.describe())

------------------------------------------------------------
E-commerce Dataset
  OrderID Product  Quantity  Price
0    O100   Phone       1.0  20000
1    O101  Laptop       2.0  60000
2    O100   Phone       1.0  20000
3    O102   Phone       NaN  15000
4    O103  Laptop       1.0  -5000
Structral summary of e-commerce data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   5 non-null      object
 1   Product   5 non-null      object
 2   Quantity  4 non-null      float64
 3   Price     5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes
None
Statictical summary of e-commerce data
       Quantity         Price
count      4.00      5.000000
mean       1.25  22000.000000
std        0.50  23611.437906
min        1.00  -5000.000000
25%        1.00  15000.000000
50%        1.00  20000.000000
75%        1.25  20000.000000
max        2.00  60000.000000

In [20]:
# removing the false data
df_ecom["Price"]=df_ecom["Price"].abs()
#Handelling missingdata and duplicates
df_ecom["Quantity"]=df_ecom["Quantity"].fillna(df_ecom["Quantity"].mode()[0])
df_ecom=df_ecom.drop_duplicates()
#encoding
df_ecom_encoded=df_ecom.copy()
# df_ecom_encoded=pd.get_dummies(df_ecom,dtype=int,columns=["Product"])
encoder=LabelEncoder()
df_ecom_encoded["Product"]=encoder.fit_transform(df_ecom_encoded["Product"])
#Droping useless columns
df_ecom_encoded=df_ecom_encoded.drop("OrderID",axis=1)
#Scaling 
columns_to_scale=["Quantity"]
df_ecom_scaled=df_ecom_encoded.copy()
scaler=StandardScaler()
df_ecom_scaled[columns_to_scale]=scaler.fit_transform(df_ecom_encoded[columns_to_scale])
#Data spliting
x=df_ecom_scaled.drop("Price",axis=1)
y=df_ecom_scaled["Price"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)